# Azure Pipeline for holochain-rust

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo ./waitforapt
    sudo apt-get update
    DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y qt4-qmake
  displayName: 'Install build prerequisites'

- script: |
    source $HOME/.cargo/env
    make test_c_ci
  displayName: 'C binding tests'
