# Azure Pipeline for holochain-rust

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- script: |
    sudo apt-get update -y
    sudo apt-get install -y qt4-qmake
  displayName: 'Install build prerequisites'

- script: |
    make test_c_ci
  env:
    PATH: $(HOME)/.cargo/bin:$(PATH)
  displayName: 'C binding tests'
