# Azure Pipeline for holochain-rust

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo apt-get update
    sudo bash -c "sleep 15 && apt-get install -y qt4-qmake"
  displayName: 'Install build prerequisites'

- script: |
    ./docker/run make test_c_ci
  displayName: 'C binding tests'
