# Azure Pipeline for holochain-rust

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo ./waitforapt
    sudo apt-get update
    DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y qt4-qmake libqt4-dev
  displayName: 'Install build prerequisites'

- script: |
    export PATH=$HOME/.cargo/bin:$PATH
    make test_c_ci
  displayName: 'C binding tests'

- script: |
    export PATH=$HOME/.cargo/bin:$PATH
    make code_coverage && bash <(curl -s https://codecov.io/bash)
  displayName: "Standard tests + code coverage"

- script: |
    export PATH=$HOME/.cargo/bin:$PATH
    make fmt_check
    make clippy
  displayName: "Formatting & clippy"

- script: |
    export PATH=$HOME/.cargo/bin:$PATH
    make install_mdbook
    ./travis-update-book.sh
  env:
    ENCRYPTION_LABEL: "30dd9296640e"
    COMMIT_AUTHOR_EMAIL: "connor.turland@holo.host"
  displayName: "Mdbook Build"