# Azure Pipeline for holochain-rust

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    sudo ./waitforapt
    sudo apt-get update
    DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y qt4-qmake libqt4-dev
  displayName: 'Install build prerequisites'

- script: |
    export PATH=$HOME/.cargo/bin:$PATH
    make test_c_ci
  displayName: 'C binding tests'
