# Azure Pipeline for holochain-rust

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    # Workaround known issue where the VM agent has a lock on Aptitude package manager for a while
    while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do
      sleep 1
    done
  displayName: 'Temp workaround: Wait for apt lock to be released'

- script: |
    sudo apt-get update
    DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y qt4-qmake libqt4-dev
  displayName: 'Install build prerequisites'

- script: |
    export PATH=$HOME/.cargo/bin:$PATH
    make test_c_ci
  displayName: 'C binding tests'

- script: |
    export PATH=$HOME/.cargo/bin:$PATH
    make install_ci
    make code_coverage && bash <(curl -s https://codecov.io/bash)
  displayName: "Standard tests + code coverage"

- script: |
    export PATH=$HOME/.cargo/bin:$PATH
    make fmt_check
    make clippy
  displayName: "Formatting & clippy"

- script: |
    export PATH=$HOME/.cargo/bin:$PATH
    make install_mdbook
    ./travis-update-book.sh
  env:
    ENCRYPTION_LABEL: "30dd9296640e"
    COMMIT_AUTHOR_EMAIL: "connor.turland@holo.host"
  displayName: "Mdbook Build"